# -*- coding: utf-8 -*-
from __future__ import unicode_literals

ORIGIN_API = 'API'
ORIGIN_RULE = 'RULE'
ORIGIN_DEV = 'DEV'
ORIGIN_CHOICES = (
    (ORIGIN_API, 'Api'),
    (ORIGIN_RULE, 'Rule'),
    (ORIGIN_DEV, 'Device'),
)

STATUS_INI = 'INI'
STATUS_ERR = 'ERR'
STATUS_CON = 'CON'
STATUS_NO_CON = 'NO_CON'
STATUS_CHOICES = (
    (STATUS_INI, 'Inicial'),
    (STATUS_ERR, 'Error'),
    (STATUS_CON, 'Conectado'),
    (STATUS_NO_CON, 'Desconectado'),
)

CHIP_STATUS_FREE = 'FREE'
CHIP_STATUS_CALL = 'CALL'
CHIP_STATUS_IN_CALL = 'IN_CAL'
CHIP_STATUS_ERR = 'ERR'
CHIP_STATUS_CHOICES = (
    (CHIP_STATUS_FREE, 'Libre'),
    (CHIP_STATUS_CALL, 'Llamando'),
    (CHIP_STATUS_IN_CALL, 'En llamada'),
    (CHIP_STATUS_ERR, 'Error'),
)

LOG_DEVICE_STATUS_INI = 'INI'
LOG_DEVICE_STATUS_PRO = 'PRO'
LOG_DEVICE_STATUS_OK = 'OK'
LOG_DEVICE_STATUS_ERR = 'ERR'
LOG_DEVICE_STATUS_CAN = 'CAN'
LOG_DEVICE_STATUS_CHOICES = (
    (LOG_DEVICE_STATUS_INI, 'Inicial'),
    (LOG_DEVICE_STATUS_PRO, 'Procesando'),
    (LOG_DEVICE_STATUS_OK, 'Ok'),
    (LOG_DEVICE_STATUS_ERR, 'Error'),
    (LOG_DEVICE_STATUS_CAN, 'Cancelada'),
)

LOG_DEVICE_TYPE_ERR = 'ERR'
LOG_DEVICE_TYPE_STATUS = 'STATUS'
LOG_DEVICE_TYPE_CALL = 'CALL'
LOG_DEVICE_TYPE_IN_CALL = 'CALL'
LOG_DEVICE_TYPE_NEWSMS = 'NEWSMS'
LOG_DEVICE_TYPE_SMS = 'SMS'
LOG_DEVICE_TYPE_CHOICES = (
    (LOG_DEVICE_TYPE_ERR, 'Error'),
    (LOG_DEVICE_TYPE_STATUS, 'Estado'),
    (LOG_DEVICE_TYPE_CALL, 'CALL'),
    (LOG_DEVICE_TYPE_IN_CALL, 'IN_CALL'),
    (LOG_DEVICE_TYPE_NEWSMS, 'NEWSMS'),
    (LOG_DEVICE_TYPE_SMS, 'SMS'),
)

LOG_ACTION_STATUS_INI = 'INI'
LOG_ACTION_STATUS_PRO = 'PRO'
LOG_ACTION_STATUS_OK = 'OK'
LOG_ACTION_STATUS_ERR = 'ERR'
LOG_ACTION_STATUS_CAN = 'CAN'
LOG_ACTION_STATUS_CHOICES = (
    (LOG_ACTION_STATUS_INI, 'Inicial'),
    (LOG_ACTION_STATUS_PRO, 'Procesando'),
    (LOG_ACTION_STATUS_OK, 'Ok'),
    (LOG_ACTION_STATUS_ERR, 'Error'),
    (LOG_ACTION_STATUS_CAN, 'Cancelada'),
)

LOG_ACTION_TYPE_CALL = 'CALL'
LOG_ACTION_TYPE_ANSW = 'ANSW'
LOG_ACTION_TYPE_HOFF = 'HOFF'
LOG_ACTION_TYPE_SMS = 'SMS'
LOG_ACTION_TYPE_RSMS = 'RSMS'
LOG_ACTION_TYPE_DSMS = 'DSMS'
LOG_ACTION_TYPE_CHOICES = (
    (LOG_ACTION_TYPE_CALL, 'Llamar'),
    (LOG_ACTION_TYPE_ANSW, 'Atender'),
    (LOG_ACTION_TYPE_HOFF, 'Cortar'),
    (LOG_ACTION_TYPE_SMS, 'Enviar SMS'),
    (LOG_ACTION_TYPE_RSMS, 'Leer SMS'),
    (LOG_ACTION_TYPE_DSMS, 'Eliminar SMSs'),
)

TO_CHIP_STATUS = {
    0: CHIP_STATUS_FREE,
    2: CHIP_STATUS_ERR,
    3: CHIP_STATUS_CALL,
    4: CHIP_STATUS_IN_CALL
}
