# Generated by Django 2.2.4 on 2019-08-30 03:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_rule_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='logaction',
            name='date_ok',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='logdevice',
            name='date_ok',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='index_sms',
            field=models.IntegerField(default=0),
        ),
    ]
