# Generated by Django 2.2.4 on 2019-08-20 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruleinstance',
            old_name='log',
            new_name='log_device',
        ),
        migrations.RemoveField(
            model_name='logdevice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ruleinstance',
            name='status',
        ),
        migrations.AddField(
            model_name='device',
            name='index_sms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='logaction',
            name='rule_instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='devices.RuleInstance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rule',
            name='origin',
            field=models.CharField(choices=[('API', 'Api'), ('RULE', 'Rule'), ('DEV', 'Device')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rule',
            name='to_type',
            field=models.CharField(choices=[('CALL', 'CALL'), ('SMS', 'SMS'), ('API', 'API')], max_length=10, null=True),
        ),
    ]
