# Generated by Django 2.2.4 on 2019-08-23 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20190822_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logaction',
            name='rule_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.RuleInstance'),
        ),
    ]
