# Generated by Django 2.2.4 on 2019-09-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20190830_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='last_rule_date',
        ),
        migrations.AlterField(
            model_name='device',
            name='chip_status',
            field=models.CharField(choices=[('FREE', 'Libre'), ('CALL', 'Llamando'), ('IN_CALL', 'En llamada'), ('ERR', 'Error')], default='FREE', max_length=10),
        ),
        migrations.AlterField(
            model_name='logdevice',
            name='log_type',
            field=models.CharField(choices=[('ERR', 'Error'), ('STATUS', 'Estado'), ('CALL', 'CALL'), ('IN_CALL', 'IN_CALL'), ('NEWSMS', 'NEWSMS'), ('SMS', 'SMS')], max_length=10),
        ),
    ]
