# -*- coding: utf-8 -*-
from __future__ import unicode_literals

RULE_STRATEGY_DEFAULT = 'DEF'
RULE_STRATEGY_CHOICES = (
    (RULE_STRATEGY_DEFAULT, 'Default'),
)

RULE_TYPE_DEVICE = 'DEV'
RULE_TYPE_ACTION = 'ACT'
RULE_TYPE_CHOICES = (
    (RULE_TYPE_DEVICE, 'Device'),
    (RULE_TYPE_ACTION, 'Action'),
)

# RULE_FROM_TYPE_CALL = 'CALL'
# RULE_FROM_TYPE_SMS = 'SMS'
# RULE_FROM_TYPE_API = 'API'
# RULE_FROM_TYPE_CHOICES = (
#     (RULE_FROM_TYPE_CALL, 'CALL'),
#     (RULE_FROM_TYPE_SMS, 'SMS'),
#     (RULE_FROM_TYPE_API, 'API'),
# )

# RULE_TO_TYPE_CALL = 'CALL'
# RULE_TO_TYPE_SMS = 'SMS'
# RULE_TO_TYPE_API = 'API'
# RULE_TO_TYPE_CHOICES = (
#     (RULE_TO_TYPE_CALL, 'CALL'),
#     (RULE_TO_TYPE_SMS, 'SMS'),
#     (RULE_TO_TYPE_API, 'API'),
# )
