# -*- coding: utf-8 -*-
from __future__ import unicode_literals

RULE_TYPE_DEFAULT = 'DEF'
RULE_TYPE_CHOICES = (
    (RULE_TYPE_DEFAULT, 'Default'),
)

RULE_FROM_TYPE_CALL = 'CALL'
RULE_FROM_TYPE_SMS = 'SMS'
RULE_FROM_TYPE_API = 'API'
RULE_FROM_TYPE_CHOICES = (
    (RULE_FROM_TYPE_CALL, 'CALL'),
    (RULE_FROM_TYPE_SMS, 'SMS'),
    (RULE_FROM_TYPE_API, 'API'),
)

RULE_TO_TYPE_CALL = 'CALL'
RULE_TO_TYPE_SMS = 'SMS'
RULE_TO_TYPE_API = 'API'
RULE_TO_TYPE_CHOICES = (
    (RULE_TO_TYPE_CALL, 'CALL'),
    (RULE_TO_TYPE_SMS, 'SMS'),
    (RULE_TO_TYPE_API, 'API'),
)

RULE_STATUS_OK = 'OK'
RULE_STATUS_ERR = 'ERR'
RULE_STATUS_CHOICES = (
    (RULE_STATUS_OK, 'Ok'),
    (RULE_STATUS_ERR, 'Error'),
)
