# Generated by Django 2.2.4 on 2019-08-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('DEV', 'Device'), ('ACT', 'Action')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rule',
            name='strategy',
            field=models.CharField(choices=[('RES_SMS', 'Respond SMS')], max_length=10),
        ),
    ]
