# Generated by Django 2.2.4 on 2019-09-01 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rules', '0002_auto_20190830_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleinstance',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='ruleinstance',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
