# Generated by Django 2.2.4 on 2019-10-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_auto_20190901_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleinstance',
            name='is_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='strategy',
            field=models.CharField(choices=[('RES_SMS', 'Respond SMS'), ('LIS_LOG', 'Listen SMS & CALL')], max_length=10),
        ),
    ]
